[package]
name = "bmap"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "MAP file memory analyzer"
repository = "https://github.com/bmap"

[dependencies]
futures-util = "0.3.31"
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
open = "5.3.2"
rust-embed = "8.8.0"
tokio = { version = "1.52.0", features = ["full"] }
mapfile_parser = { version = "2.12", features = ["serde"] }
url = "2"
rfd = "0.17.2"
iced = { version = "0.14", features = ["tokio", "wgpu"] }
